# Generated by Django 4.2.5 on 2023-10-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="course",
            name="lab",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="lecture",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="seminar",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name="CourseGradingComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradeapp.course",
                    ),
                ),
                (
                    "grading_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradeapp.gradingcomponent",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "grading_component")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="grading_component",
            field=models.ManyToManyField(
                through="gradeapp.CourseGradingComponent",
                to="gradeapp.gradingcomponent",
            ),
        ),
    ]
