# Generated by Django 4.2.5 on 2023-10-04 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "gradeapp",
            "0002_gradingcomponent_alter_category_options_course_lab_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("date", models.DateField()),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Finished", "Finished"),
                            ("Cancelled", "Cancelled"),
                            ("Urgent!", "Urgent!"),
                        ],
                        default="Not Started",
                        max_length=100,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradeapp.course",
                    ),
                ),
                (
                    "grading_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradeapp.gradingcomponent",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
