# Generated by Django 4.2.5 on 2023-10-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0003_event_remove_assignment_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="grade",
        ),
        migrations.AddField(
            model_name="event",
            name="max_grade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="student_grade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
