# Generated by Django 4.2.5 on 2023-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0005_alter_event_options_todoitems"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="todoitems",
            name="progress",
            field=models.CharField(default="Not Started", max_length=100),
        ),
    ]
