# Generated by Django 4.2.5 on 2023-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0006_progress_alter_todoitems_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitems",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
