# Generated by Django 4.2.5 on 2023-10-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0008_todoitem_delete_todoitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="progress",
        ),
    ]
