# Generated by Django 4.2.5 on 2023-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0009_remove_event_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="progress_style",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
