# Generated by Django 4.2.5 on 2023-10-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0010_todoitem_progress_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="progress_style",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="progress_style",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="gradeapp.progress"
            ),
        ),
    ]
