# Generated by Django 4.2.5 on 2023-10-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0011_remove_todoitem_progress_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="progress_style",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name="todoitem",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="todoitem",
            name="progress_style",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="progress",
            field=models.ManyToManyField(blank=True, null=True, to="gradeapp.progress"),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="progress_style",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
