# Generated by Django 4.2.5 on 2023-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0012_progress_progress_style_remove_todoitem_progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progress",
            name="progress_style",
        ),
        migrations.RemoveField(
            model_name="todoitem",
            name="progress",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="progress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
