# Generated by Django 4.2.5 on 2023-10-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0014_category_todoitem_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
