# Generated by Django 4.2.5 on 2023-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradeapp", "0015_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="category_style",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
